### ISSUE TITLE
The SSblup problem

### ISSUE THREAD

**Issue by Yansen0515** [ABGG-UGA/blupf90-public#8]
Dear group,
The new tutorial blupf90 (2019) maybe has a problem, in “8.5 GWAS using the ssGBLUP framework”, I download the data from http://nce.ads.uga.edu/wiki/lib/exe/fetch.php?media=lab_gwas.zip - lab_gaws.zip, then run it. But when I do the “bash s1.sh”, the computer give me the information:

 cp: impossible d'évaluer 'snp_sol': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer 'chrsnp': Aucun fichier ou dossier de ce type
awk: cannot open snp_sol (No such file or directory)

![image](https://user-images.githubusercontent.com/55590706/65332604-4b4bb500-dbbf-11e9-9344-824f01d053b1.png)

.
So I try did it used one by one parameter file, but when I run the blupf90(renf90.par), there also had this problem.
Can you check the data?

Kind regard,
Yansen

**Comment by Yansen0515** [comment]
If you do that, please tell me, my e-mail: yansen0515@gmail.com,

**Comment by masuday** [comment]
Thank you for the report. The tool chain of ssGWAS has changed since I wrote the tutorial. I will check the files.

**Comment by Yansen0515** [comment]
Hi,
I think that I find a problem. The SNP position of chrmap data is  needs to
be an integer， but when I run s2.sh, i met a new problem. I hope you can
check this whole ssGWAS command.

kind regards,

*Yansen CHEN*
*PhD student*

University of Liège - Gembloux Agro-Bio Tech (GxABT)
Agriculture, Bio-engineering and Chemistry Department
Animal Science Unit
Numerical Genetics, Genomics and Modeling

Avenue de la faculté d'agronomie, 8
5030 Gembloux
Belgium

Phone: 0032 494.12.57.25
E-mail: yansen.chen@doct.uliege.be
           yansen0515@gmail.com
Website: https://www.gembloux.uliege.be/cms/c_4039827/nl/portail-gembloux


Yutaka Masuda <notifications@github.com> 于2019年9月23日周一 下午12:07写道：

**Comment by masuday** [comment]
The script `s1.sh` and `s2.sh` were not really useful for the tutorial. Also, the tutorial had some outdated descriptions about ssGWAS. I have updated the files and the scripts in the tutorial. Please read the new version (https://github.com/masuday/Blupf90TutorialStandard).

**Comment by Yansen0515** [comment]
Ok, thanks.

Sent from Mail for Windows 10
